### PR TITLE
A ab fixdeletebutton

### PR DESCRIPTION
**Pull request by An-AngryBear**
made our multi array system work off of one singular array. this allows us to run functions on that array and whenever there is a change to the dom we can just update the message box with that singular array.  I also fixed minor bugs and made it uniform

### CODE REVIEW

**Comment by hayleylandsberg** [comment]
Awesome!!! Looks great!

**Comment by Rian501** [comment]
:+1:
Yeah I just fetched this and it is working just like it is supposed to, as far as I can tell!
You gonna have to walk me through what you did!! 🗡 
Okay I tried to make the colon-capital-d-face ( 😁 ) but it input dagger instead. I thought that was kind of funny.

**Comment by cait-rocco** [comment]
looks good! i can't test it (git fetch hasn't been working for me). is this part in dom interaction:
addMessages.pushJsonToCurrentArray = function(jsonArray) {
 +		combinedArray = jsonArray;

not considered bad hard coding of another module into that module?

**Comment by An-AngryBear** [comment]
> so all the json stuff happens on the first line in main.js

```Chatty.LoadMessages.retrieveMessages(Chatty.DOMInteraction.assignIds, `Chatty.DOMInteraction.pushJsonToCurrentArray);```

before we didnt have the "pushJsonToCurrentArray" part we just had the assignIds part being passed to the retrieve messages method. So i'm essentially  just passing in 'pushJsonToCurrentArray' in addition to what we already had (both come from DOM interaction and are being passed into our JSON Fetcher.)

so lets go to the **JSON fetcher** module, to the retrieveMessages method

i believe emily worked with joe on the json fetcher to make sure she was doing it right and at the time she had named her callback "cb" -- i just changed the name of that to "assignIDFunc" for clarity since it will basically become 'assignIds' which we just passed in on **main.js**. the assignIDFunc just comes along for the ride to be called later. the pushJsonToCurrentArray  that we passed in on **main.js** becomes the jsonToArrayFunc argument and will be called on 'load'. so we'll pretend it loads and setMessages gets called passing in assignIDsFunc. setMessages puts the json messages in an array and then runs assignIDs on that array -- assignIDs does its assigning IDs business in the **DOMInteraction module**. after the IDs getsassigned, its get stuck in the DOM and that is how json messages get in the dom first thing.

after all this stuff happens and json gets put into the DOM then jsonToArrayFunc gets called (which again is just the pushJsonToCurrentArray that we passed in at the top of **main.js**)

jsonToArrayFunc takes in the message array that we just established in the previous step and makes it the beginning of the combinedArray on **DOM Interaction** --from there on we can add our user messages, we can clear it, and we can remove individual messages. Any time we want to see what is in the array we can call  Chatty.DOMInteraction.getUserMessages() for an updated instance.

so the jsonArr argument on "pushJsonToCurrentArray" in **DOMInteraction** isn't a hard coded array, in my opinion, it is dynamic and will adapt to whatever is being passed into it. I just chose jsonarr as the argument name so it would be more clear to what its used for.

**Comment by An-AngryBear** [comment]
in short the first line of main.js does 3 things:

grabs the crap in the json file,
puts it in the dom with ids,
puts it in our array that we can manipulate at any time.

**Pull request merged**
